"""watcherz

Revision ID: a6dbc9f42506
Revises: c0ad3953df44
Create Date: 2025-03-31 20:51:40.635196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6dbc9f42506'
down_revision = 'c0ad3953df44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('isGoat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isGoat', sa.VARCHAR(length=10), nullable=False))

    # ### end Alembic commands ###
