"""12345

Revision ID: dad3f6c55e3e
Revises: ffdc0a98111c
Create Date: 2025-03-31 20:41:39.559630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad3f6c55e3e'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isGoat', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('firstName', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('lastName', sa.String(length=40), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')
        batch_op.drop_column('isGoat')

    # ### end Alembic commands ###
