"""create_watchlist_cryptos_table

Revision ID: a05f05e2c5cb
Revises: 4901d01e474d
Create Date: 2025-04-10 18:10:04.438360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05f05e2c5cb'
down_revision = '4901d01e474d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_cryptos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), sa.ForeignKey("watchlists.id"), nullable=False),
    sa.Column('crypto_id', sa.Integer(), sa.ForeignKey("cryptos.id"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_cryptos')
    # ### end Alembic commands ###
